# Generated by Django 5.2.1 on 2025-05-15 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('machine_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('polling_interval', models.PositiveIntegerField(default=5)),
                ('enabled', models.BooleanField(default=True)),
                ('os_name', models.CharField(max_length=100)),
                ('os_version', models.CharField(max_length=100)),
                ('architecture', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=200)),
                ('cpu_cores', models.IntegerField()),
                ('cpu_threads', models.IntegerField()),
                ('total_ram', models.FloatField()),
                ('total_storage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SnapshotBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.machine')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('ppid', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('cpu_usage', models.FloatField()),
                ('memory_usage', models.FloatField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='core.snapshotbatch')),
            ],
        ),
        migrations.CreateModel(
            name='MachineSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_ram', models.BigIntegerField()),
                ('used_ram', models.BigIntegerField()),
                ('available_ram', models.BigIntegerField()),
                ('total_disk', models.BigIntegerField()),
                ('used_disk', models.BigIntegerField()),
                ('available_disk', models.BigIntegerField()),
                ('network_sent', models.BigIntegerField()),
                ('network_received', models.BigIntegerField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_snapshots', to='core.snapshotbatch')),
            ],
        ),
    ]
