# Generated by Django 5.2.1 on 2025-05-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='os_version',
        ),
        migrations.AlterField(
            model_name='machine',
            name='total_ram',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='machine',
            name='total_storage',
            field=models.IntegerField(),
        ),
    ]
