# Generated by Django 5.2.1 on 2025-05-15 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_machine_os_version_alter_machine_total_ram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinesnapshot',
            name='batch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='machine_snapshot', to='core.snapshotbatch'),
        ),
    ]
