# Generated by Django 5.2.1 on 2025-05-16 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_machinesnapshot_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinesnapshot',
            name='network_received',
        ),
        migrations.RemoveField(
            model_name='machinesnapshot',
            name='network_sent',
        ),
    ]
